# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: aws-ssosync
  description: Deploys [AWS ssosync](https://github
  homepage: https://cloudposse.com/accelerate
  topics: terraform, terraform-component
